### ISSUE TITLE
How to use ICFG

### ISSUE THREAD

**Issue by g252691665** [secure-software-engineering/soot-infoflow-android#129]
Dear developers,
I have  created a JimpleBasedInterproceduralCFG  and got a ICFG, but I do not know how to use it,Could you give me some examples.thank you very much.
Best wishes!

**Comment by StevenArzt** [comment]
What is your goal? What data do you want to obtain from the ICFG? I need a bit more context to give any helpful advice on the topic.

**Comment by g252691665** [comment]
Thanks for your answer,my goal is  to obtain all nodes and edges so that I can make it visible and do some operations on it, Similar to graph traversal.

**Comment by StevenArzt** [comment]
That is actually pretty easy as shown below:

```
	public static void main(String[] args) throws IOException, XmlPullParserException {
		// Initialize Soot
		SetupApplication analyzer = new SetupApplication("C:\\Program Files (x86)\\Android\\android-sdk\\platforms",
				"D:/org.fdroid.k9_17046.apk");
		analyzer.getConfig().setTaintAnalysisEnabled(false);
		analyzer.calculateSourcesSinksEntrypoints(Collections.emptySet(), Collections.emptySet());
		analyzer.runInfoflow();
		
		// Iterate over the callgraph
		for (Iterator<Edge> edgeIt = Scene.v().getCallGraph().iterator(); edgeIt.hasNext(); ) {
			Edge edge = edgeIt.next();
			
			SootMethod smSrc = edge.src();
			Unit uSrc = edge.srcStmt();
			SootMethod smDest = edge.tgt();
			
			System.out.println("Edge from " + uSrc + " in " + smSrc + " to " + smDest);
		}
	}
```

**Comment by g252691665** [comment]
Dear StevenArzt
Thanks for your answer,you may misunderstand what I mean .I want to obtain all nodes and edges of ICFG and traverse the ICFG but not call graph,would you mind give me some answer about ICFG.
Best wishes!

**Comment by StevenArzt** [comment]
Oh, sorry for the misunderstanding. An ICFG is equally simple to handle. After the call to runInfoflow(), just create an instance of the InfoflowCFG class. It contains methods to get the successor and predecessor of statements as well as caller/callee relationships.

**Comment by g252691665** [comment]
Dear StevenArzt:
It does work,thanks for your answer,
Best wishes!

**Comment by loyacin** [comment]
Dear StevenArzt,
I am in the impossibility to achieve your solution.
In fact, I don't know how to get the successor of the call of a function (virtual invoke).
Do you have any recommandation please?

**Comment by ericbodden** [comment]
@g252691665 I think the method you are looking for is just called "succs".

**Comment by loyacin** [comment]
Thank you. It is exactly what I was looking for.



De : Eric Bodden <notifications@github.com>
Envoyé : jeudi 11 mai 2017 13:10
À : secure-software-engineering/soot-infoflow-android
Cc : Loïc Ricaud; Manual
Objet : Re: [secure-software-engineering/soot-infoflow-android] How to use ICFG (#129)
 


@g252691665 I think the method you are looking for is just called "succs".
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by loyacin** [comment]
Dear Mr. Bodden,

I would have two more questions for you about the ICFG:
- In the implementation of the class [SetupApplication](https://github.com/flankerhqd/JAADAS/blob/master/soot-infoflow-android/src/soot/jimple/infoflow/android/SetupApplication.java) at the line 716, they use the function`getiCfg()` from the class `InfoFlow`. Unfortunately, I wasn't able to find the documentation for this class. Hence, I was wondering if this function is protected or private, because I can't use it with my InfoFlow object. Can you tell me which answer is the good or link me to the right place please? 
- To pass through the ICFG, I'm using the `getSuccsOf(Unit u)` function. When it is a call statement, I'm branching into the function via the method `getCalleesOfCallAt(Unit u)`. I was asking myself if it was the right way to do it or if there was a way to generate the ICFG and to go through it with only the successor method? 

Thank you very much in advance for your time and your answer.

**Comment by malindadoo** [comment]
This is regards to the code given in second comment of @StevenArzt 
`	public static void main(String[] args) throws IOException, XmlPullParserException {
		// Initialize Soot
		SetupApplication analyzer = new SetupApplication("C:\\Program Files (x86)\\Android\\android-sdk\\platforms",
				"D:/org.fdroid.k9_17046.apk");
		analyzer.getConfig().setTaintAnalysisEnabled(false);
		analyzer.calculateSourcesSinksEntrypoints(Collections.emptySet(), Collections.emptySet());
		analyzer.runInfoflow();
		
		// Iterate over the callgraph
		for (Iterator<Edge> edgeIt = Scene.v().getCallGraph().iterator(); edgeIt.hasNext(); ) {
			Edge edge = edgeIt.next();
			
			SootMethod smSrc = edge.src();
			Unit uSrc = edge.srcStmt();
			SootMethod smDest = edge.tgt();
			
			System.out.println("Edge from " + uSrc + " in " + smSrc + " to " + smDest);
		}
	}
`
What are the imports (packages) that need to be done for above code ?

**Comment by malindadoo** [comment]
This is regarding the code extract given in the second comment of @StevenArzt 
![capture](https://user-images.githubusercontent.com/20140049/28925708-434fc75c-7883-11e7-8331-9c681a3f9580.JPG)

What are the import (packages) that need to be done for the code ?

**Comment by StevenArzt** [comment]
For this code to work, you need soot, soot-infoflow, and soot-infoflow-android.

**Comment by malindadoo** [comment]
Could you please let me know the maven repository for soot-infoflow. I got maven repository for soot-infoflow-android as below. 
`        <dependency>
                <groupId>de.tud.sse</groupId>
                <artifactId>soot-infoflow-android</artifactId>
                <version>2.0.0-SNAPSHOT</version>
        </dependency>`

**Comment by mbenz89** [comment]
```
    <dependencies>
       <dependency>
            <groupId>de.tud.sse</groupId>
            <artifactId>soot-infoflow</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>soot-snapshot</id>
            <name>soot snapshots</name>
            <url>https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/</url>
        </repository>
    </repositories>
```
