### ISSUE TITLE
apk compiled by android studio can not analyzed by FlowDroid

### ISSUE THREAD

**Issue by wuhonglei** [secure-software-engineering/soot-infoflow-android#133]
i have run a apk compiled by **Android Studio** on FLowDroid, the output of this tool is always ` No sources or sinks found, aborting analysis` no matter what i coding.
The funny thing is that the apk compiled by **eclipse** can be analyzed by FlowDroid.

**Comment by JulianSchuette** [comment]
Can you confirm you are not building with Android Studio's "Instant Run"
feature? It builds an APK which dynamically loads the actual application
code at runtime. This might break the analysis.

Cheers,
Julian

**Comment by Madison0831** [comment]
Hi, can you teach me how did you import this to android studio. I tried to clone it but I get so many errors. Please teach me... I really need it

**Comment by StevenArzt** [comment]
@Madison0831 Do you try to import the analysis into Android Studio? That won't work, because the FlowDroid analyzer is a Java program, not an Android app.

@wuhonglei @JulianSchuette To analyze secondary dex files, you need to enable Soot's "process-multiple-dex" option by changing the SootConfigForAndroid class.

**Comment by Msbeih** [comment]
I can use soot and flowdroid with Android studio or just Eclipse ?

**Comment by leonnewton** [comment]
@wuhonglei Could you tell me how you solve this problem?
