### ISSUE TITLE
NullPointerException when creating callgraph by constructCallgraph()

### ISSUE THREAD

**Issue by f-kanei** [secure-software-engineering/soot-infoflow-android#150]
Hello,

I’m trying to create callgraph by constructCallgraph() in SetupApplication class.
```java
SetupApplication app = new SetupApplication(platformsDir, inputApk);
app.constructCallgraph();
```
And I get the following error:
```java
Exception in thread "main" java.lang.NullPointerException
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1199)
	at soot.jimple.infoflow.android.SetupApplication.constructCallgraph(SetupApplication.java:1034)
	at com.test.Test.main(Test.java:9)
```

Is this the correct way to use constructCallgraph() ?
Thanks!

**Comment by mbenz89** [comment]
Hi,
I'm experiencing the same issue.

The exception is thrown [here](https://github.com/secure-software-engineering/soot-infoflow-android/blob/develop/src/soot/jimple/infoflow/android/SetupApplication.java#L1203) since _getSources()_ and _getSinks()_ return null if calling _runInfoflow_ through _constructCallgraph()_.

Might it be that _constructCallgraph()_ is not supported anymore? I belive I saw a check on _config.isTaintAnalysisEnabled()_ in some previous version of _runInfoflow_ but I can't find it right now.

Cheers,
Manuel

**Comment by StevenArzt** [comment]
That is indeed a bug, thanks for letting me know. I have fixed the issue. The constructCallgraph() method was introduced in FlowDroid 2.0 as a replacement for some rather clumsy method calls that were previously required in cases in which you just wanted a callgraph, but not a full-blown data flow analysis.
