### ISSUE TITLE
Has SetupApplication.calculateSourcesSinksEntrypoints  changed ?

### ISSUE THREAD

**Issue by doo1234** [secure-software-engineering/soot-infoflow-android#157]
Hi I am struggling to use following code at draw CFG of an android application. 
![image](https://user-images.githubusercontent.com/20140049/28954969-67c096ca-7900-11e7-9afc-87682ab63c85.png)

Following are the my dependency libs
`        <dependency>
                <groupId>de.tud.sse</groupId>
                <artifactId>soot-infoflow-android</artifactId>
                <version>2.0.0-SNAPSHOT</version>
        </dependency>
`
`        <dependency>
            <groupId>soot</groupId>
            <artifactId>soot</artifactId>
            <version>2.5.0</version>
        </dependency>`

Problems are- 
When I compile above code it gives an error saying 'calculateSourcesSinksEntrypoints' does not exists.( together with several other errors). When I  check the class SetupApplication in the downloaded lib soot-infoflow-android, I could not see the method as error says. When I check the history of the class SetupApplication, I saw several modifications has been done for the above method. But in the develop branch that method exists without arguments. I am little bit confused here. 
1. Can't I use the given code sample above further? If then can you please give an example code piece. 
2. Isn't <version>2.0.0-SNAPSHOT</version> the latest version of soot-infoflow-android?

**Comment by mbenz89** [comment]
If you just want to have a call graph without the full data flow analysis, just call constructCallGraph.

This is the correct soot dependency:
```
        <dependency>
            <groupId>ca.mcgill.sable</groupId>
            <artifactId>soot</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
```

**Comment by malindadoo** [comment]
Thank you very much for the answer. 

My goal is to identify all API calls of .apk and perform the analysis about the implementation of such API calls and modify the apk if required. I hope soot-inflow-android is a good library for analyzing, modifying and repacking the apks. Since I am new to soot-inflow-android I am struggling to fulfill my requirement doing basic analysis tasks. 
As the first attempt I am trying to draw the control graph in a apk file (I hope this would lead me to setup the project)
I just did as you suggested as below. 
public void constructCallgraphApk(){

    SetupApplication analyzer = new SetupApplication("D:\\android-platforms-master",
            "D:\\apks\\zekitez.com.satelliteestimator.apk");
    analyzer.getConfig().setTaintAnalysisEnabled(false);
    analyzer.constructCallgraph();

It gives the following error. 

> Callback definition file not found.

Quetions - 
1. It seems the AndroidCallbacks.txt file have not been positioned correctly in the project. 
Since I am running this as a InteliJ mavan project in windows could you please help me to position AndroidCallbacks.txt correctly ?

2. As I noticed, previously this library asked for a Source and Sink file due to unavailability of Main method in apk file. Isn't this required further? If it is, how this is going on now?

**Comment by mbenz89** [comment]
soot-infoflow-android aka FlowDroid will help you generating a call graph for Android applications and is also your go to framework for data flow analysis on Android. Nevertheless, implementing your own analysis will require a basic understanding of Soot. I recommend having a look in the wiki on how to proceed: https://github.com/sable/soot/wiki

1. The best way to handle this is to put AndroidCallbacks.txt in your resources folder and then call 
 setupApplication.setCallbackFile(getClass().getClassLoader().getResource("AndroidCallbacks.txt").getFile()); .
You can acquire the file either from the maven jar or directly download it [here](https://github.com/secure-software-engineering/soot-infoflow-android/blob/develop/AndroidCallbacks.txt).

2. You should not need a Source and Sink file if you are just going to generate a call graph with FlowDroid. The file is needed for its taint analysis feature, where an analysis tries to find data flows between sources and sinks.

Manuel

**Comment by malindadoo** [comment]
Thank you very much for the information. I could successfully update the path of AndroidCallbacks.txt as you suggested and go ahead. Removed the line `analyzer.getConfig().setTaintAnalysisEnabled(false)` from the code. Thank you again.

**Comment by LouisonGitzinger** [comment]
Hi,

I'm trying to use infoflow-android taint analysis feature in my code, in this case, how can I specify the SourcesAndSinks.txt file in the soot-infoflow-android 2.0 version ?
Thx
