### ISSUE TITLE
Flowdroid returns a non-deterministic set of source->sink flows

### ISSUE THREAD

**Issue by lazaroclapp** [secure-software-engineering/soot-infoflow-android#31]
I have been running flowdroid (soot.jimple.infoflow.android.TestApps.Test with default parameters) on a bunch of APKs, multiple times for each APK; and in some cases I am getting different sets of source to sink flows. This means not only different paths, but source->sink pairs that only appear during some of the runs. Is this sort of non-determinism expected?

One possibility I can think of, knowing that flowdroid is multi-threaded, is that there is some global resource with some sort of budget limit, forcing flowdroid to perform less precise analysis on some paths after that limit is exhausted. But I am not sure if this is the correct explanation. If not, does someone know why this would happen?

**Comment by ClaudioRizzo** [comment]
Hi, it seems like the bug is still there and it also affects the context-sensitive mode. I am not sure whether it is the same source as the one in the topic. But what I am experiencing is the following: running the same analysis (on the same apk) multiple times, reports a different number of flows.  Is there any update on this ?

**Comment by StevenArzt** [comment]
This is an outdated version of FlowDroid. Please switch to https://github.com/secure-software-engineering/FlowDroid.
