### ISSUE TITLE
<java.lang.Object: boolean equals(java.lang.Object)> as sink?

### ISSUE THREAD

**Issue by majestyhao** [secure-software-engineering/soot-infoflow-android#93]
How to declare \<java.lang.Object: boolean equals(java.lang.Object)\> as a sink so that makes all  method "equals()" of variant instances will be the sink? I added the line but FlowDroid fails to find sinks of \<java.lang.String: boolean equals(java.lang.Object)\>.

**Comment by StevenArzt** [comment]
You should add \<java.lang.Object: boolean equals(java.lang.Object)>.

**Comment by majestyhao** [comment]
As I mentioned, I have already add  <java.lang.Object: boolean equals(java.lang.Object)>,  but FlowDroid fails to find sinks of <java.lang.String: boolean equals(java.lang.Object)>.

**Comment by StevenArzt** [comment]
Oh, sorry. I misunderstood your question. The problem is that you need to add the signature of the sink. If a class does not overwrite the equals() method, the line I mentioned above works. If a class, however, overwrites equals(), then calls to equals() can be semantically different. So if you know that Object.equals() is a sink, this does not directly mean that String.equals() is also a sink, because the String class overwrites equals(). Theoretically, it could do something completely different that has nothing to do with a sink. Therefore, we by design do not include overwritten methods when considering sinks.

If you want all equals() methods even if they are overwritten and might so something completely different, you can implement your own SourceSinkManager which is derived from DefaultSourceSinkManager and provide a more flexible implementation of isSink(). FlowDroid has been designed to be extensible with custom components such as adapted source/sink managers.

Again, sorry for not properly reading your question. It's late ^^

**Comment by majestyhao** [comment]
Thank you and good night.
