### ISSUE TITLE
Dead  loop

### ISSUE THREAD

**Issue by wjk20120522** [secure-software-engineering/soot-infoflow-android#99]
I run flowDroid with a test apk. It seems run into a dead loop. The output like this:

[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Ran into a constructor generation loop for class com.meituan.android.base.ui.BaseWebFragment, substituting with null...
[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Ran into a constructor generation loop for class com.sankuai.meituan.category.CategoryFragment, substituting with null...
[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Ran into a constructor generation loop for class com.sankuai.meituan.model.datarequest.category.Category, substituting with null...
[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Constructor cannot be generated for callback class com.meituan.passport.dialogs.e

Is is Bug?

**Comment by StevenArzt** [comment]
That's absolutely normal. FlowDroid tries to create an instance of a class. There are only constructors that need arguments, so FlowDroid also needs to create those arguments. If there is a loop, e.g., the constructor of a class A requires an object of type A itself, we cannot create an A to pass it into an A which is then passed into an A... You get the idea. In that case, we cannot fully resolve the parameters and create something we can put in there. In this case, we report such a warning and just take null instead of a proper object.
